/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.frontend.presentation.view;

import java.awt.Color;
import java.awt.Component;
import java.awt.Font;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/**
 *
 * @author elkin
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        // 1) Modelo de tabla
        DefaultTableModel model = new DefaultTableModel(
                new Object[][]{},
                new String[]{"ID", "Modelo", "Marca", "Placa", "Chasis", "Año", "Color"}
        ) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        tableVehiculos.setModel(model);

        // 2) Altura de fila
        tableVehiculos.setRowHeight(24);

        // 3) Estilo de cabecera
        JTableHeader header = tableVehiculos.getTableHeader();
        header.setFont(header.getFont().deriveFont(Font.BOLD, 14f));
        header.setBackground(new Color(60, 63, 65));
        header.setForeground(Color.WHITE);
        DefaultTableCellRenderer headerRenderer
                = (DefaultTableCellRenderer) header.getDefaultRenderer();
        headerRenderer.setHorizontalAlignment(JLabel.CENTER);

        // 4) Zebra striping y selección
        tableVehiculos.setDefaultRenderer(Object.class, new DefaultTableCellRenderer() {
            private final Color EVEN = new Color(240, 240, 240);
            private final Color ODD = Color.WHITE;

            @Override
            public Component getTableCellRendererComponent(
                    JTable tbl, Object value, boolean isSelected,
                    boolean hasFocus, int row, int col) {
                Component c = super.getTableCellRendererComponent(
                        tbl, value, isSelected, hasFocus, row, col);
                if (isSelected) {
                    c.setBackground(new Color(57, 105, 138));
                    c.setForeground(Color.WHITE);
                } else {
                    c.setBackground((row % 2) == 0 ? EVEN : ODD);
                    c.setForeground(Color.BLACK);
                }
                setBorder(noFocusBorder);
                return c;
            }
        });

        // 5) Líneas de rejilla suaves
        tableVehiculos.setShowGrid(true);
        tableVehiculos.setGridColor(new Color(200, 200, 200));

    }

    public JComboBox<String> getComboMarca() {
        return comboMarca;
    }

    public JComboBox<String> getComboModelo() {
        return comboModelo;
    }

    public JComboBox<String> getComboColor() {
        return comboColor;
    }

    public JTextField getTxtPlaca() {
        return txtPlaca;
    }

    public JTextField getTxtChasis() {
        return txtChasis;
    }

    public JTextField getTxtAnio() {
        return txtAnio;
    }

    public JButton getBtnLoadCatalogs() {
        return btnLoadCatalogs;
    }

    public JButton getBtnCreateVehiculo() {
        return btnCreateVehiculo;
    }

    public JButton getBtnDeleteVehiculo() {
        return btnDeleteVehiculo;
    }

    public JButton getBtnClearForm() {
        return btnClearForm;
    }

    public JTable getTableVehiculos() {
        return tableVehiculos;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        comboColor = new javax.swing.JComboBox<>();
        comboMarca = new javax.swing.JComboBox<>();
        comboModelo = new javax.swing.JComboBox<>();
        btnLoadCatalogs = new javax.swing.JButton();
        btnCreateVehiculo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableVehiculos = new javax.swing.JTable();
        txtPlaca = new javax.swing.JTextField();
        txtChasis = new javax.swing.JTextField();
        txtAnio = new javax.swing.JTextField();
        btnDeleteVehiculo = new javax.swing.JButton();
        btnClearForm = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(214, 234, 248));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        comboColor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(comboColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 190, 120, -1));

        comboMarca.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboMarca.setPreferredSize(new java.awt.Dimension(70, 20));
        jPanel1.add(comboMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 154, 120, -1));

        comboModelo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboModelo.setMinimumSize(new java.awt.Dimension(70, 20));
        comboModelo.setPreferredSize(new java.awt.Dimension(70, 20));
        jPanel1.add(comboModelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 154, 120, -1));

        btnLoadCatalogs.setFont(new java.awt.Font("Roboto Black", 0, 12)); // NOI18N
        btnLoadCatalogs.setText("Cargar Catálogos");
        btnLoadCatalogs.setPreferredSize(new java.awt.Dimension(132, 22));
        jPanel1.add(btnLoadCatalogs, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, -1, 30));

        btnCreateVehiculo.setFont(new java.awt.Font("Roboto Black", 0, 12)); // NOI18N
        btnCreateVehiculo.setText("Guardar Vehículo");
        btnCreateVehiculo.setMaximumSize(new java.awt.Dimension(123, 22));
        btnCreateVehiculo.setMinimumSize(new java.awt.Dimension(123, 22));
        btnCreateVehiculo.setPreferredSize(new java.awt.Dimension(132, 22));
        btnCreateVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateVehiculoActionPerformed(evt);
            }
        });
        jPanel1.add(btnCreateVehiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 240, -1, 30));

        tableVehiculos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableVehiculos);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 291, 720, 402));

        txtPlaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPlacaActionPerformed(evt);
            }
        });
        jPanel1.add(txtPlaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 154, 71, -1));
        jPanel1.add(txtChasis, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 154, 71, -1));
        jPanel1.add(txtAnio, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 195, 71, -1));

        btnDeleteVehiculo.setFont(new java.awt.Font("Roboto Black", 0, 12)); // NOI18N
        btnDeleteVehiculo.setText("Eliminar Vehículo");
        btnDeleteVehiculo.setPreferredSize(new java.awt.Dimension(132, 22));
        jPanel1.add(btnDeleteVehiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 240, -1, 30));

        btnClearForm.setFont(new java.awt.Font("Roboto Black", 0, 12)); // NOI18N
        btnClearForm.setText("Limpiar Formulario");
        jPanel1.add(btnClearForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 240, -1, 30));

        jLabel1.setFont(new java.awt.Font("Roboto Black", 1, 24)); // NOI18N
        jLabel1.setText("GESTIÓN DE VEHÍCULOS");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 40, -1, -1));

        jLabel2.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        jLabel2.setText("Datos del Vehículo");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 118, 160, -1));

        jLabel4.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        jLabel4.setText("Placa:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 154, 48, -1));

        jLabel5.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        jLabel5.setText("Marca:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 154, 50, -1));

        jLabel6.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        jLabel6.setText("Chasis:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 154, 50, -1));

        jLabel7.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        jLabel7.setText("Modelo:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 154, 60, -1));

        jLabel8.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        jLabel8.setText("Año:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 195, -1, -1));

        jLabel9.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        jLabel9.setText("Color:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 195, 40, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/carro-didi.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 30, 140, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, 755));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateVehiculoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCreateVehiculoActionPerformed

    private void txtPlacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPlacaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPlacaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClearForm;
    private javax.swing.JButton btnCreateVehiculo;
    private javax.swing.JButton btnDeleteVehiculo;
    private javax.swing.JButton btnLoadCatalogs;
    private javax.swing.JComboBox<String> comboColor;
    private javax.swing.JComboBox<String> comboMarca;
    private javax.swing.JComboBox<String> comboModelo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableVehiculos;
    private javax.swing.JTextField txtAnio;
    private javax.swing.JTextField txtChasis;
    private javax.swing.JTextField txtPlaca;
    // End of variables declaration//GEN-END:variables
}
